version: '3'
services:
  mlflow-deploy:
    build:
      context: ./ml-flow-docker
      dockerfile: deploy.Dockerfile
    user: root:root
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - MODEL_ID=${MODEL_ID}
    ports:
      - "1234:1234"
    volumes:
      - ./ml-flow-docker/data:/mlflow

  proxy-mlflow:
    build:
      context: ./ml-flow-docker
      dockerfile: proxy.Dockerfile
    command: "python3 proxy-mlflow.py"
    ports:
      - "8090:8090"
    links:
      - mlflow-deploy
