version: '3'
services:
  notebook:
    build:
      context: ./jupyter-notebook-docker
    user: root:root
    ports:
      - "8888:8888"
    depends_on: 
      - mlflow
    environment: 
      MLFLOW_TRACKING_URI: 'http://mlflow:5000'
    volumes: 
      - ./jupyter-notebook-docker/data:/home/jovyan
      - ./ml-flow-docker/data:/mlflow
  mlflow:
    build:
      context: ./ml-flow-docker
    expose: 
      - "5000"
    user: root:root
    ports:
      - "5000:5000"
    volumes:
      - ./ml-flow-docker/data:/mlflow
    depends_on: 
      - postgres
  postgres:
    build:
      context: ./postgres-docker
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'secret'
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-store:/var/lib/postgresql/data
